### ISSUE TITLE
Request not from admin network (flask.json)

### ISSUE THREAD

**Issue by ruirigel** [aaronwmorris/indi-allsky#1222]
I can't flush the images and time lapses because I'm accessing the panel remotely, outside the network. As I have little space on the SDcard, how can I stop the app from saving the images but still showing them in Latest? or How can I flush if I'm not on the same network as the machine?

Thank you,
Rui

![Captura de ecrã 2024-04-13 113055](https://github.com/aaronwmorris/indi-allsky/assets/24510121/15db35e0-c078-4abf-b92b-278551481009)

**Comment by aaronwmorris** [comment]
This is just an additional safety mechanism I added to prevent unauthorized deleting of files.  Most times this is because your traffic is being connected via IPv6.  In the newer releases of indi-allsky, I added better dynamic detection of your local networks for both IPv4 and IPv6 so this has become less of a problem.

You can override this check by adding `0.0.0.0/0` and `::/0` to `/etc/indi-allsky/flask.json` in the `ADMIN_NETWORKS` variable.

```
  "ADMIN_NETWORKS": [
    "10.0.0.0/8",
    "192.168.0.0/16",
    "172.16.0.0/12",
    "169.254.0.0/16",
    "fe80::/64",
    "127.0.0.1/32",
    "::1/128",
    "0.0.0.0/0",
    "::/0"
  ],
```
