### ISSUE TITLE
Error generating star trail

### ISSUE THREAD

**Issue by Dentonknifeworks** [aaronwmorris/indi-allsky#260]
This is on a new install.
The error code is #408 Not enough images found to build star trail.
Timelaps is good and so is the Kegogram.
Jul 13 16:34:08 CamCamper [WARNING] VideoWorker001 starTrails.finalize() #129: Star trails images processed in 0.0 s
Jul 13 16:34:08 CamCamper [WARNING] VideoWorker001 starTrails.finalize() #130: Excluded 2128 images
Jul 13 16:34:08 CamCamper [ERROR] VideoWorker001 video.generateKeogramStarTrails() #408: Error generating star trail: Not enough images found to build star trail
Jul 13 16:34:08 CamCamper [WARNING] VideoWorker001 video.generateKeogramStarTrails() #412: Total keogram/star trail processing in 53.3 s
[indi-allsky 2.log.zip](https://github.com/aaronwmorris/indi-allsky/files/9106488/indi-allsky.2.log.zip)

**Comment by Dentonknifeworks** [comment]
Sample image
![ccd2_20220713_000012](https://user-images.githubusercontent.com/64991600/178848370-fe0a69b7-4a50-4077-9811-a22bb89764af.jpg)

![ccd2_20220713_000012](https://user-images.githubusercontent.com/64991600/178848351-afd329e8-a5f4-47dd-8ae2-2d4e7cf96511.jpg)
e

**Comment by aaronwmorris** [comment]
This is not unusual for full moon nights.  Most (or all of the frames) end up being excluded because they are too bright.  The exclusion algorithm is pretty aggressive to ensure only the darkest images are used.  You could try raising the `Star Trails Max ADU` setting to something like 80 to try to get more images included.

In the situation above, you may also considering setting the `SQM/Star Region of Interest` setting to only encompass open sky in the image.  The brightness in the trees could cause all of the images to be excluded.

In fairness, in cases where no images are selected, I should add at least one image so an image is generated for startrails.

**Comment by aaronwmorris** [comment]
Merged #261 so that there is always at least one image used for star trails.

**Comment by Dentonknifeworks** [comment]
That works!
Looks much better than a broken Icon image.
Thanks
