### ISSUE TITLE
Disk space buffer to prevent website going down

### ISSUE THREAD

**Issue by dbainbridge** [aaronwmorris/indi-allsky#527]
If you completely run out of disk space:
`[ERROR] MainProcess indi.newBLOB() #233: OSError: Not enough space on disk: requested 12879360, available 0. Not enough space on disk: requested 12879360, available 0. 6439680 requested and 5938368 written `
which happened at 5:30AM this morning by the time I checked the web site around 7:30AM the web page simply responded with an "internal server error".  

Wondering if there is some way to keep the service from using every last byte of space and then causing the website to fail.

This also appears to have caused the VideoWorker to become stuck even after I cleared up disk space manually from the disk and then rebooted the system.  The VideoWorker task that is supposed to be generating the Timelapse's has been stuck running for couple hours now.  I believe it will only fix itself after the hard 6 hour time limit?  In any event it gets into some stuck state after ran out of disk space earlier.

**Comment by aaronwmorris** [comment]
My guess is it may be the star trail timelapse which requires a significant amount of disk space to generate.  Each image in the sequence has to be saved (temporarily) in order to generate the trails timelapse.   The files are deleted when finished, but with a 1920x1080 (1K) image resolution, on a good moonless night, this can require 1+GB of space.  If you have a 4K camera, it could need 2-4 GB of available disk space.
