### ISSUE TITLE
After manual time update, allsky doesn't take images

### ISSUE THREAD

**Issue by sifank** [aaronwmorris/indi-allsky#554]
RPI is not connected to the internet so it starts up with a date about a month ago.  Allsky starts up and is taking images but dated a month ago (of course).  When I click on the 'Update Time', the correct time (from the browser) is set, but then allsky starts reporting Exposure State: BUSY and Camera last ready: keeps climbing.

I have to restart the indiserver and then the allsky services to get everything taking pictures with the right time.

I just updated to PR553 to check if this is still happening - it is.  

I also disabled GPS and ran setup.py telling it no GPS, just to isolate this behavior.

This sequence keeps repeating itself in the log:
Feb  4 17:06:08 allskysqm [INFO] MainProcess allsky.run() #932: Camera last ready: 2345846.2s
Feb  4 17:06:08 allskysqm [INFO] MainProcess allsky.run() #933: Exposure state: BUSY
Feb  4 17:06:08 allskysqm [INFO] MainProcess allsky.detectNight() #1502: Sun altitude: 3:01:25.0
Feb  4 17:06:08 allskysqm [INFO] MainProcess allsky.detectMoonMode() #1519: Moon altitide: 5:46:13.7, phase 99.3%
Feb  4 17:06:08 allskysqm [INFO] MainProcess indi.getCcdTemperature() #849: Sensor temperature: 28.2
Feb  4 17:06:08 allskysqm [INFO] MainProcess indi.getTelescopeRaDec() #834: Telescope Coord: RA 1.82, Dec 44.87
Feb  4 17:06:08 allskysqm [INFO] MainProcess allsky._queueManualTasks() #2295: Checking for manually submitted tasks

**Comment by aaronwmorris** [comment]
Remind me what camera you are using?  ASI294?

**Comment by sifank** [comment]
Yes, ASI294.  But I've noticed this on an ASI120 as well.

Sifan
Carpe Nocturnum ...

**Comment by aaronwmorris** [comment]
I will have to add a note in the time configuration page that the indiserver and indi-allsky may need a full start when changing the time.

If you notice above it says the exposure state is busy.  That message is because the camera server is still reporting the camera is still taking an exposure.  Depending on how the camera driver is tracking the time, suddenly changing the time can cause a race condition where things never complete.  And each camera server has different code, so the behavior would not be consistent between vendors.

Specific to indi-allsky:  Changing the time forward in indi-allsky should be safe, but setting time backwards could cause some very strange issues.

**Comment by aaronwmorris** [comment]
Merged #572 with the additional warning.

**Comment by sifank** [comment]
Would it be possible to restart both the indiserver and the indi-allsky when updating the time?

**Comment by aaronwmorris** [comment]
It would be possible, but I am not sure how many problems that could cause.

I have considered updating the code to only set the time when the camera is not actively taking a frame, but that is a fairly complex workflow, as well.

**Comment by aaronwmorris** [comment]
I tried updating the code to only update time between exposures, but it not help.  Moving forward in time works consistently, but moving backwards almost always causes the exposure control to get stuck in the Busy state.

**Comment by aaronwmorris** [comment]
Closing for now.
